coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 1%
        branches: 
          - main
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: true
